[Common]
SERVER_PORT = "8088"      #服务端口号
SERVER_READTIMEOUT = 5    #单位 秒
SERVER_WRITETIMEOUT = 30  #单位 秒
VERSION = ""

ACCESS_LOG = "/tmp/letsgo_access.log"
ERROR_LOG = "/tmp/letsgo_error.log"

BASEAUTH = false
BASEAUTH_SALTKEY = "123456"

EXAMPLE_INFO_CACHE_EXPIRE = 600 #超时设置 单位：秒
CONFIG_CACHE_EXPIRE = 600 #config缓存失效时间 单位：秒

StatusOk = 1    #ok
StatusNoData = 2    #无数据
StatusParamsNoValid = 3     #参数错误
StatusError = 4     #异常

[MySQL]
  [MySQL.Vrs]
    [MySQL.Vrs.Master]
      Host = "127.0.0.1"      #IP地址  
      Port = "3306"           #端口
      User = "time2k"         #用户名 
      Password = "legend123"  #密码
      DBname = "vrs"          #表名
      DBcharset = "utf8"      #字符集  
      DBconnMaxConns = 20     #最大连接数
      DBconnMaxIdles = 2      #最大空闲连接
      DBconnMaxLifeTime = 1800  #单位：秒
    [[MySQL.Vrs.Slave]]
      Host = "127.0.0.1"
      Port = "3306"
      User = "time2k"
      Password = "legend123"
      DBname = "vrs"
      DBcharset = "utf8"
      DBconnMaxConns = 20
      DBconnMaxIdles = 2
      DBconnMaxLifeTime = 1800  #单位：秒

[Memcached]
  Expire = 600
  Timeout = 5 #单位：秒
  IdleConns = 40
  [[Memcached.Servers]]
    Host = "127.0.0.1"
    Port = "11211"
  
[CacheHttp]
  DialTimeout = 2 #http dial 超时，包含DNS时间 单位：秒
  ResponseTimeout = 2 #http响应超时 单位：秒
  ChannelBufferLen = 10 #
  DowngradeCacheExpire = 60 #
  SelectTimeout = 10 #单位： 秒

[Schedule]
  ChannelBufferLen = 20 #调度器channel buffer长度
  MaxConcurrent = 20
  SelectTimeout = 10 #单位： 秒

[Redis]
  [[Redis.Servers]]
    Host = "10.124.132.46"
    Port = "6509"
    Password = ""
    ConnectTimeout = 5 #单位： 秒
    ReadTimeout = 5 #单位： 秒
  [[Redis.Servers]]
    Host = "10.124.132.47"
    Port = "6509"
    Password = ""
    ConnectTimeout = 5 #单位： 秒
    ReadTimeout = 5 #单位： 秒
  [[Redis.Servers]]
    Host = "10.124.132.112"
    Port = "6509"
    Password = ""
    ConnectTimeout = 5 #单位： 秒
    ReadTimeout = 5 #单位： 秒

[AreaListRev]
  "美国" = "us"
  "英国" = "uk"
  "日本" = "jp"
  "韩国" = "kr"
  "泰国" = "th"
  "中国" = "cn"
  "中国大陆" = "cn"
  "中国台湾" = "cn"
  "中国香港" = "hk"
  "香港" = "hk"
  "内地" = "cn"
  "大陆" = "cn"
  "港澳台" = "hmt"
  "欧美" = "ue"
  "其他" = "other"

[Demote]  #降级对应处理函数,因为不支持key中包含"."故将域名中的"."全部转成"_"
  "geo_mob_app_letv2_com/geo" = "GetVideoInfo"


# name = "Tom Preston-Werner"
# organization = "GitHub"
# bio = "GitHub Cofounder & CEO\nLikes tater tots and beer."
# dob = 1979-05-27T07:32:00Z # 日期时间是一等公民。为什么不呢？

# [database]
# server = "192.168.1.1"
# ports = [ 8001, 8001, 8002 ]
# connection_max = 5000
# enabled = true

# [servers]

#   # 你可以依照你的意愿缩进。使用空格或Tab。TOML不会在意。
#   [servers.alpha]
#   ip = "10.0.0.1"
#   dc = "eqdc10"

#   [servers.beta]
#   ip = "10.0.0.2"
#   dc = "eqdc10"

# [clients]
# data = [ ["gamma", "delta"], [1, 2] ]

# # 在数组里换行没有关系。
# hosts = [
#   "alpha",
#   "omega"
# ]